import { Providers } from "@src/components/provider/provider";
import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";

const nunito = Nunito({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-nunito",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${nunito.className} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
